name: Run Tests on Multiple Versions of PostgreSQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Lint
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
          go vet ./...

  test:
    strategy:
      matrix:
        postgres-version: [10, 11, 12, 15, 17]
    runs-on: ubuntu-latest
    container: golang:alpine

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 54${{ matrix.postgres-version }}:5432

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL (client)
        run: |
          apk --update add postgresql-client

      - name: Check PostgreSQL version
        run: |
          psql --version
      
      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        env:
          PGMGR_TEST_HOST: postgres
          PGHOST: postgres
          PGPORT: 54${{ matrix.postgres-version}}
          PGMGR_TEST_PORT: 54${{ matrix.postgres-version}}
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          go test -timeout=30s ./...
